version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building Storybook...
      - npm run build-storybook
      - echo Building Site...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  secondary-artifacts:
    site:
      name: site-artifact
      base-directory: dist
      files:
        - "**/*"
    storybook:
      name: storybook-artifact
      base-directory: storybook-static
      files:
        - "**/*"
